### ISSUE TITLE
Could you guide me in how to modify the code to input mxnx3 images that are binary labelled into the lstm system?

### ISSUE THREAD

**Issue by alexanderdumont** [andrewfry/SharpML-Recurrent#2]
Hi andrew. Great work on adapting this great code into c#. I was wondering if we could adapt this code to work on inputted jpg images of different or same size and get out a binary classifier. THank you

**Comment by andrewfry** [comment]
I would not suggest this library. This was more an experiment for me to improve my understanding of RNN. Take a look at NUML or CNTK. Good luck.
