### ISSUE TITLE
LSTM network does not improve through training

### ISSUE THREAD

**Issue by Plystire** [andrewfry/SharpML-Recurrent#3]
I replaced the FeedForward network in ExampleXor.cs with a similarly initialized Lstm network from NetworkBuilder.
Running this, it can be seen that the network's error does not improve over time.

The Gru and Rnn networks appear to improve over time in the example project.

I am not too familiar yet with the intricacies of LSTMs, so I am taking my time decoding your implementation of GRU and comparing against some articles I am researching. 
I really appreciate the effort you've made here! It has helped me quite a lot in understanding neural networks and how the fancy maths translate into code. So, thank you! :)

**Comment by andrewfry** [comment]
Hey sorry for the delayed reply. This project was for educational purposes and has many bugs. I do not maintain it. If you want to use recurrent nets in C# I suggest looking into CNTK, which is creating a C# API or looking at TensorFlowSharp, which is a C# wrapper for TensorFlow. https://github.com/migueldeicaza/TensorFlowSharp and https://github.com/Microsoft/CNTK
